# Generated by Django 5.2.7 on 2025-10-13 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('partner_type', models.CharField(choices=[('ngo', 'Non-Governmental Organization'), ('gov', 'Government/Police'), ('corp', 'Corporate Sponsor')], max_length=10)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_verified_partner', models.BooleanField(default=False, help_text='Checked by site admin for full access.')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_set', models.CharField(choices=[('search', 'Search Party'), ('tech', 'Tech/Coding'), ('design', 'Graphic Design/Posters'), ('admin', 'Administrative Support'), ('other', 'Other')], default='other', max_length=50)),
                ('availability', models.TextField(blank=True, help_text='Details on when they can help.')),
                ('application_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Active'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Volunteer Applications',
            },
        ),
    ]
