# Generated by Django 5.2.7 on 2025-10-13 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0002_sighting_tip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('checklist', 'First 48 Hours Checklist'), ('legal', 'Legal Aid Directory'), ('health', 'Mental Health Support'), ('other', 'Other Useful Guide')], default='other', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Full text content of the resource (e.g., checklist steps).', null=True)),
                ('link_url', models.URLField(blank=True, help_text='URL to an external resource or downloadable file.', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='If false, only visible to authenticated users/admins.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Resources',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FamilySupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Brief subject of the support request.', max_length=255)),
                ('support_message', models.TextField(help_text='Detailed message requesting support.')),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('moderator_notes', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(blank=True, help_text='Optional: Link to a specific missing person report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='reports.report')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Family Support Requests',
                'ordering': ['-contacted_at'],
            },
        ),
    ]
