# Generated by Django 5.2.7 on 2025-10-10 15:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(help_text='Age in years.', validators=[django.core.validators.MinValueValidator(0)])),
                ('age_range', models.CharField(choices=[('minor', 'Minor (Under 18)'), ('adult', 'Adult (18+)'), ('unknown', 'Unknown Age')], default='unknown', max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('last_seen_date', models.DateTimeField()),
                ('last_seen_location', models.CharField(help_text="Specific place, e.g., 'Meskel Square, Addis Ababa'", max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified - Active'), ('resolved', 'Resolved - Found'), ('unfounded', 'Unfounded/False Report')], default='pending', max_length=20)),
                ('description', models.TextField(help_text='Detailed physical description, clothing, and circumstances.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/photos/%Y/%m/%d/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
